### ISSUE TITLE
Make the fetching script and this repo more reliable

### ISSUE THREAD

**Issue by moul** [gnolang/tx-exports#1]
I was running it on a personal server, but we should make something more reliable.

Tagging @albttx and @zivkovicmilos for attention, but others are welcome to contribute as well

**Comment by leohhhn** [comment]
@moul 

We've merged #5, which will serve as a tool to help make this repo more reliable. In relation to #6, what would you like this repo to become? The extractor is finished in itself, but it needs to be integrated into a CI that will stay up to date with the chain. I am waiting on an update on tx-archive to implement this CI.

**Comment by thehowl** [comment]
this repository now uses tx-archive, exports repositories, is [deterministic](https://github.com/gnolang/tx-exports/commit/bb457f7b96dad04467dc69b358f71185f84599a5) and is automatically run on the CI.

i'll close this issue as it generally is more reliable; it now has some more specific issues to tackle.
