### ISSUE TITLE
Consider making the source extraction straight in this repo.

### ISSUE THREAD

**Issue by moul** [gnolang/tx-exports#2]
See https://github.com/gnolang/hackerspace/issues/39.

Could be enough to just have a subfolder like `src/{testnet}/{p,r}/...`.

Tagging @albttx, @waymobetta, and @leohhhn for attention, but others are welcome to contribute as well.

**Comment by leohhhn** [comment]
@moul 

Extractor service that works in tandem with @zivkovicmilos' [tx-archive tool](https://github.com/gnolang/tx-archive/) is in reviews currently (PR #5). I propose a refactor to this repo:
- Remove the .log files
- Remove extraction script
- Merge extractor PR
- Have a central folder (ie. `archive`) for the extracted source code.

We can configure GH actions to activate the extractor service once the archiving service is done with its work.

**Comment by leohhhn** [comment]
This has been completed in #5 & #14.
