### ISSUE TITLE
unstable portal loop backup

### ISSUE THREAD

**Issue by moul** [gnolang/tx-exports#24]
![CleanShot 2024-11-01 at 22 54 58](https://github.com/user-attachments/assets/9b918b4f-bfe3-45a6-86c0-c10e16794897)

It seems the script is no longer functioning. 

Could you please:  
1. Check if we are losing something when it turns red, or if that data is simply not backed up?  
2. Work on making it more stable?  
Thank you.

**Comment by moul** [comment]
Blocking https://github.com/gnolang/gno/pull/3024

**Comment by zivkovicmilos** [comment]
Resolved with #25
