### ISSUE TITLE
Generate reports

### ISSUE THREAD

**Issue by moul** [gnolang/tx-exports#8]
The PR #7 modified the repository structure for improvement, but it unintentionally removed certain features, such as the automatic snapshot report that includes specific data.

Please refer to: https://github.com/gnolang/tx-exports/commit/ab618c587610609178d9d81ed1b9248b251d79d4

@albttx or @gnolang/devrels, could you kindly attempt a reset for this issue? It seems that the report scripts might still be present, but they are possibly no longer being called. Alternatively, we may need to create new scripts.

**Comment by leohhhn** [comment]
Closing as backup & extractor is running in CI currently.
